name: CI

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "21.6"

      - name: Build
        run: npm install && npm run docs:build

      - name: Tencent COS and CDN
        uses: sylingd/tencent-cos-and-cdn-action@latest
        with:
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          cos_bucket: ${{ secrets.BUCKET }}
          cos_region: ap-shanghai
          cos_accelerate: false
          cdn_prefix: https://blog.yizhou.ac.cn
          local_path: .vitepress/dist/
          remote_path: /
          clean: false