name: CI

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "10.x"

      - name: Build
        run: npm install && npm run docs:build

      - name: Deploy
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r ./.vitepress/dist/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-shanghai